export type ProfileStatus =
  | "start"
  | "draft"
  | "submitted"
  | "fileChecked"
  | "fileRejected"
  | "invitedToInterview"
  | "notInvitedToInterview"
  | "passedInterview"
  | "failedInterview"
  | "paymentAccepted"
